# Generated by Django 5.0.14 on 2026-06-27 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estado_ordenes', '0001_initial'),
        ('nivel_tueste', '0001_initial'),
        ('tueste', '0007_add_inventario_cafe_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleTueste',
            fields=[
                ('id', models.AutoField(db_column='IdDetalleTueste', primary_key=True, serialize=False)),
                ('fecha_ingreso', models.DateTimeField(blank=True, db_column='FechaIngreso', null=True)),
                ('numero_batch', models.IntegerField(db_column='NumeroBatche')),
                ('kilos_verde', models.FloatField(blank=True, db_column='KilosVerde', null=True)),
                ('kilos_tostado', models.FloatField(blank=True, db_column='KilosTostado', null=True)),
                ('observaciones', models.CharField(blank=True, db_column='Observaciones', max_length=500, null=True)),
                ('estado_orden', models.ForeignKey(blank=True, db_column='IdEstadoOrden', null=True, on_delete=django.db.models.deletion.SET_NULL, to='estado_ordenes.estadoorden')),
                ('nivel_tueste', models.ForeignKey(blank=True, db_column='IdNivelTueste', null=True, on_delete=django.db.models.deletion.SET_NULL, to='nivel_tueste.niveltueste')),
                ('tueste', models.ForeignKey(db_column='IdOrdenTueste', on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='tueste.tueste')),
            ],
            options={
                'db_table': 'tblDetalleTueste',
                'ordering': ['numero_batch', 'id'],
            },
        ),
    ]
