# Generated by Django 5.0.14 on 2026-09-26 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calidad',
            name='peso_defecto',
            field=models.FloatField(blank=True, db_column='PesoDefecto', null=True),
        ),
    ]
