# Generated by Django 5.0.14 on 2026-09-28 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0002_calidad_peso_defecto'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalisisSensorial',
            fields=[
                ('id', models.BigAutoField(db_column='Id', primary_key=True, serialize=False)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True, db_column='FechaIngreso')),
                ('nombre', models.CharField(db_column='Nombre', max_length=120)),
                ('fecha', models.DateField(db_column='Fecha')),
                ('objetivo', models.CharField(blank=True, db_column='Objetivo', max_length=200)),
                ('muestra_numero', models.CharField(db_column='MuestraNumero', max_length=60)),
                ('nivel_tueste', models.PositiveSmallIntegerField(blank=True, db_column='NivelTueste', null=True)),
                ('intensidad_fragancia', models.DecimalField(blank=True, db_column='IntensidadFragancia', decimal_places=1, max_digits=4, null=True)),
                ('intensidad_aroma', models.DecimalField(blank=True, db_column='IntensidadAroma', decimal_places=1, max_digits=4, null=True)),
                ('descriptores_fragancia_aroma', models.TextField(blank=True, db_column='DescriptoresFraganciaAroma', default='[]')),
                ('notas_fragancia_aroma', models.TextField(blank=True, db_column='NotasFraganciaAroma')),
                ('intensidad_sabor', models.DecimalField(blank=True, db_column='IntensidadSabor', decimal_places=1, max_digits=4, null=True)),
                ('intensidad_sabor_residual', models.DecimalField(blank=True, db_column='IntensidadSaborResidual', decimal_places=1, max_digits=4, null=True)),
                ('descriptores_sabor', models.TextField(blank=True, db_column='DescriptoresSabor', default='[]')),
                ('gustos_predominantes', models.TextField(blank=True, db_column='GustosPredominantes', default='[]')),
                ('notas_sabor', models.TextField(blank=True, db_column='NotasSabor')),
                ('intensidad_acidez', models.DecimalField(blank=True, db_column='IntensidadAcidez', decimal_places=1, max_digits=4, null=True)),
                ('notas_acidez', models.TextField(blank=True, db_column='NotasAcidez')),
                ('intensidad_dulzor', models.DecimalField(blank=True, db_column='IntensidadDulzor', decimal_places=1, max_digits=4, null=True)),
                ('notas_dulzor', models.TextField(blank=True, db_column='NotasDulzor')),
                ('intensidad_sensacion_boca', models.DecimalField(blank=True, db_column='IntensidadSensacionBoca', decimal_places=1, max_digits=4, null=True)),
                ('sensaciones_boca', models.TextField(blank=True, db_column='SensacionesBoca', default='[]')),
                ('notas_sensacion_boca', models.TextField(blank=True, db_column='NotasSensacionBoca')),
                ('notas_extrinseca', models.TextField(blank=True, db_column='NotasExtrinseca')),
                ('calidad_fragancia', models.PositiveSmallIntegerField(blank=True, db_column='CalidadFragancia', null=True)),
                ('calidad_aroma', models.PositiveSmallIntegerField(blank=True, db_column='CalidadAroma', null=True)),
                ('notas_afectiva_fragancia_aroma', models.TextField(blank=True, db_column='NotasAfectivaFraganciaAroma')),
                ('calidad_sabor', models.PositiveSmallIntegerField(blank=True, db_column='CalidadSabor', null=True)),
                ('calidad_sabor_residual', models.PositiveSmallIntegerField(blank=True, db_column='CalidadSaborResidual', null=True)),
                ('notas_afectiva_sabor', models.TextField(blank=True, db_column='NotasAfectivaSabor')),
                ('calidad_acidez', models.PositiveSmallIntegerField(blank=True, db_column='CalidadAcidez', null=True)),
                ('notas_afectiva_acidez', models.TextField(blank=True, db_column='NotasAfectivaAcidez')),
                ('calidad_dulzor', models.PositiveSmallIntegerField(blank=True, db_column='CalidadDulzor', null=True)),
                ('notas_afectiva_dulzor', models.TextField(blank=True, db_column='NotasAfectivaDulzor')),
                ('calidad_sensacion_boca', models.PositiveSmallIntegerField(blank=True, db_column='CalidadSensacionBoca', null=True)),
                ('notas_afectiva_sensacion_boca', models.TextField(blank=True, db_column='NotasAfectivaSensacionBoca')),
                ('impresion_global', models.PositiveSmallIntegerField(blank=True, db_column='ImpresionGlobal', null=True)),
                ('notas_impresion_global', models.TextField(blank=True, db_column='NotasImpresionGlobal')),
                ('puntaje_total', models.DecimalField(blank=True, db_column='PuntajeTotal', decimal_places=2, max_digits=6, null=True)),
                ('tazas_no_uniformes', models.PositiveSmallIntegerField(db_column='TazasNoUniformes', default=0)),
                ('tazas_defectuosas', models.PositiveSmallIntegerField(db_column='TazasDefectuosas', default=0)),
                ('defectos_haberlo', models.TextField(blank=True, db_column='DefectosHaberlo', default='[]')),
            ],
            options={
                'db_table': 'tblAnalisisSensorial',
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
