# Generated by Django 5.0.14 on 2026-06-27 02:25

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_trilla', '0003_ordentrilla_notas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordentrilla',
            name='fecha_ingreso',
            field=models.DateTimeField(blank=True, db_column='FechaIngreso', db_default=django.db.models.functions.datetime.Now(), null=True),
        ),
    ]
