# Generated by Django 5.0.14 on 2026-09-18 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RagMonthlyQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(unique=True)),
                ('used', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'rag_monthly_quota',
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='RagQueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('operation', models.CharField(blank=True, default='', max_length=80)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('success', 'Exitosa'), ('failed', 'Fallida')], default='pending', max_length=12)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('quota', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='queries', to='rag.ragmonthlyquota')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rag_queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rag_query_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='idx_rag_status_created')],
            },
        ),
    ]
