# Generated by Django 5.0.14 on 2026-06-27 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_cafe', '0008_alter_inventariocafe_codigo'),
        ('variedad_cafe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventariocafe',
            name='variendad_inven_cafe',
            field=models.ForeignKey(blank=True, db_column='IdVariendadInvenCafe', null=True, on_delete=django.db.models.deletion.SET_NULL, to='variedad_cafe.variedadcafe'),
        ),
    ]
