# Generated by Django 5.0.14 on 2026-06-27 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0015_detalleempaqueorden'),
        ('variedad_cafe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='conf_sel_tostado',
            field=models.BooleanField(blank=True, db_column='ConfSelTostado', default=False, null=True),
        ),
        migrations.AlterField(
            model_name='orden',
            name='variedad_cafe',
            field=models.ForeignKey(blank=True, db_column='IdVaridadCafe', null=True, on_delete=django.db.models.deletion.SET_NULL, to='variedad_cafe.variedadcafe'),
        ),
    ]
