# Generated by Django 5.0.14 on 2026-09-13 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0016_alter_orden_conf_sel_tostado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='inventario_descontado',
            field=models.BooleanField(db_column='InventarioDescontado', default=False, editable=False),
        ),
    ]
